# Inspired by
# - https://www.backhub.co/blog/best-practices-for-using-github-issues
# - https://medium.com/nyc-planning-digital/writing-a-proper-github-issue-97427d62a20f
# - https://wiredcraft.com/blog/how-we-write-our-github-issues/
name: 💡 Request an enhancement
description: Suggest an idea for this project.
body:
- type: markdown
  attributes:
    value: |
      # Welcome
      
      Thank you very much for providing your enhancement idea, we appreciate that! 🙏
      Please describe your idea to us, so we can have a qualified discussion together and make eCAL better!
      
- type: markdown
  attributes:
    value: |
      # Enhancement suggestion
      
- type: textarea
  id: context
  attributes:
    label: Context
    description: |
      - Provide background to help others understand this issue.
      - Describe the problem or need you'd like to address.
  validations:
    required: true


- type: textarea
  id: proposal
  attributes:
    label: Proposal
    description: |
      - A simple and clear description of what you're proposing.
      - Ideas or constraints for how to implement this proposal
      - Important considerations to think about or discuss
  validations:
    required: false


- type: textarea
  id: tasks
  attributes:
    label: Tasks and updates
    description: |
      Use this area to track ongoing work and to-do items.
      The more specific the better.

      _If you can't think of anything then just leave this blank and we can fill it in later! This can be filled in as we understand more about an issue._

    placeholder: |
      - [ ] Discuss and decide on what to do...
      - [ ] Implement partial feature A...

  validations:
    required: false
