name: Build macOS

on:  
  push:
  pull_request:
    branches:
      - master

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
    - name: Install Dependencies
      run: brew install ninja protobuf

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules:  'true'
        fetch-depth: 0

    - name: CMake
      run: |
        mkdir "${{ runner.workspace }}/_build"
        cd "${{ runner.workspace }}/_build"
        cmake $GITHUB_WORKSPACE -G "Ninja" \
        -DECAL_CORE_COMPONENT_ENABLE_C_BINDING=ON \
        -DECAL_CORE_COMPONENT_ENABLE_CONFIG=ON \
        -DECAL_CORE_COMPONENT_ENABLE_PROCESS_STUB=ON \
        -DECAL_CORE_COMPONENT_ENABLE_SAMPLES=ON \
        -DECAL_CORE_COMPONENT_ENABLE_TESTS=ON \
        -DECAL_CORE_COMPONENT_INSTALL_SAMPLE_SOURCE=ON \
        -DECAL_CORE_FEATURE_ENABLE_CAPNPROTO=OFF \
        -DECAL_CORE_FEATURE_ENABLE_NPCAP=OFF \
        -DECAL_CORE_FEATURE_ENABLE_ICEORYX=OFF \
        -DECAL_CORE_THIRDPARTY_BUILD_CMAKEFUNCTIONS=ON \
        -DECAL_CORE_THIRDPARTY_BUILD_TCP_PUBSUB=ON \
        -DECAL_CORE_THIRDPARTY_BUILD_RECYCLE=ON \
        -DECAL_CORE_THIRDPARTY_BUILD_GTEST=ON \
        -DECAL_CORE_THIRDPARTY_BUILD_PROTOBUF=OFF \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_CXX_STANDARD=14
        sudo mkdir /etc/ecal
        sudo cp "$GITHUB_WORKSPACE/ecal/core/cfg/ecal.ini" /etc/ecal
      shell: bash

    - name: Build Release
      run: cmake --build . --config Release
      working-directory: ${{ runner.workspace }}/_build

    - name: Pack
      run: cpack -G DragNDrop
      working-directory: ${{ runner.workspace }}/_build

    - name: Upload DMG
      uses: actions/upload-artifact@v2
      with:
        name: macos-dmg
        path: ${{ runner.workspace }}/_build/_package/*.dmg
